# routes.yml
index:
    path:     /

logout:
    path:     /signout
    defaults: { _controller: signout }
login:
    path:     /signin
    defaults: { _controller: signin }
    methods: [POST]
register:
    path:     /signup
    defaults: { _controller: signup }
    methods:  [POST]

search_main_all:
    path:     /search/{page}
    defaults: { _controller: search, q: null, page: 1}
    requirements:
        page:  \d+

search_main:
    path:     /search/{page}/{q}
    defaults: { _controller: search, q: null, page: 1}
    requirements:
        page:  \d+

account_recipe_search:
    path:     /account/recipy/{page}/{acq}
    defaults: { _controller: account, section: 'recipy', acq: null,  page: 1}
    requirements:
            page:  \d+

account:
    path:     /account/{section}/{page}
    defaults: { _controller: account, section: 'account', page: 1}
    requirements:
                page:  \d+

recipe_add:
    path:     /recipe/add
    defaults: { _controller: recipeAdd }

recipe_edit:
    path:     /recipe/edit/{id}
    defaults: { _controller: recipeEdit }
    requirements:
            page:  \d+

recipe_show:
    path:     /recipe/{id}/{title}
    defaults: { _controller: recipe }
    requirements:
            id:  \d+
