app_recipy:
    image: silintl/php7
    dns:
        - "8.8.8.8"
    ports:
        - "63530:80"
    volumes:
        - "../:/var/www/html"
    links:
        - mariadb
#        - maildev:maildev

mariadb:
    image: bitnami/mariadb
    ports:
        - "8889:3306"
    environment:
        - MARIADB_USER=root
        - MARIADB_PASSWORD=root
        - MARIADB_DATABASE=recipy



#maildev:
#    restart: always
#    image: djfarrelly/maildev
#    ports:
#        - "1080:80"
